#ifndef IINSTSTATUS_H
#define IINSTSTATUS_H

enum InstErrCode
{
    INST_ERR_NONE = 0,
    INST_ERR_DENOISING = 1,
    INST_ERR_ECHO_CANCEL = 2,
    INST_ERR_VOICE_ACTIVE = 3,
    INST_ERR_AGC = 4,
    INST_ERR_VOICE_USER = 5,
    INST_ERR_VOL_LEVEL = 6,
    INST_ERR_TRANSMIT_ENABLED = 7,
    INST_ERR_INST_NOT_FOUND = 8,
    INST_ERR_USER_NOT_FOUND = 9,

    INST_ERR_FIXED_DENOISING = 101,
    INST_ERR_FIXED_ECHO_CANCEL = 102,
    INST_ERR_FIXED_VOICE_ACTIVE = 103,
    INST_ERR_FIXED_AGC = 104,
    INST_ERR_FIXED_VOICE_USER = 105,
    INST_ERR_FIXED_VOL_LEVEL = 106,
    INST_ERR_FIXED_TRANSMIT_ENABLED = 107
};

class IInstStatus
{
public:
    virtual void setError(int code) = 0;
};

#endif // IINSTSTATUS_H
